//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : StaticDate.h
//  @ Date : 2017/9/29
//  @ Author : 
//
//


#if !defined(_STATICDATE_H)
#define _STATICDATE_H


class StaticDate {
public:
	StaticDate sharedStaticData(int );
	void purge(int );
	int intValueForKey(std::string key);
	char stringValueFrom(std::string Key);
	float floatValueFrimKey(int Key);
	bool booleanFromKey(std::string Key);
	cocos2s::CCPoint poinFromKey(std::string Key);
	cocos2d::CCRect rectValueFrimKey(std::string Key);
	cocos2d::CCSize sizeFromKey(int Key);
protected:
	cocos2d::CCDictionary _dictionary;
	std::string _staticFileName;
	bool init(int );
private:
	~StaticDate();
	StaticData();
};

#endif  //_STATICDATE_H
